---@class lc.Imports
local imports = {}

-- Pull requests are welcome to add more imports for other languages.

imports["python3"] = {
    "from string import *",
    "from re import *",
    "from datetime import *",
    "from collections import *",
    "from heapq import *",
    "from bisect import *",
    "from copy import *",
    "from math import *",
    "from random import *",
    "from statistics import *",
    "from itertools import *",
    "from functools import *",
    "from operator import *",
    "from io import *",
    "from sys import *",
    "from json import *",
    "from builtins import *",
    "import string",
    "import re",
    "import datetime",
    "import collections",
    "import heapq",
    "import bisect",
    "import copy",
    "import math",
    "import random",
    "import statistics",
    "import itertools",
    "import functools",
    "import operator",
    "import io",
    "import sys",
    "import json",
    "from typing import *",
}

imports["python"] = {
    "from bisect import *",
    "from collections import *",
    "from copy import *",
    "from datetime import *",
    "from heapq import *",
    "from math import *",
    "from re import *",
    "from string import *",
    "from random import *",
    "from itertools import *",
    "from functools import *",
    "from operator import *",
    "import string",
    "import re",
    "import datetime",
    "import collections",
    "import heapq",
    "import bisect",
    "import copy",
    "import math",
    "import random",
    "import itertools",
    "import functools",
    "import operator",
}

imports["java"] = {
    "import java.util.*;",
    "import java.math.*;",
}

imports["cpp"] = {
    "#include <algorithm> // IWYU pragma: keep",
    "#include <array> // IWYU pragma: keep",
    "#include <bitset> // IWYU pragma: keep",
    "#include <climits> // IWYU pragma: keep",
    "#include <cmath> // IWYU pragma: keep",
    "#include <cstdint> // IWYU pragma: keep",
    "#include <deque> // IWYU pragma: keep",
    "#include <functional> // IWYU pragma: keep",
    "#include <iostream> // IWYU pragma: keep",
    "#include <limits> // IWYU pragma: keep",
    "#include <list> // IWYU pragma: keep",
    "#include <map> // IWYU pragma: keep",
    "#include <numeric> // IWYU pragma: keep",
    "#include <queue> // IWYU pragma: keep",
    "#include <set> // IWYU pragma: keep",
    "#include <stack> // IWYU pragma: keep",
    "#include <string> // IWYU pragma: keep",
    "#include <tuple> // IWYU pragma: keep",
    "#include <unordered_map> // IWYU pragma: keep",
    "#include <unordered_set> // IWYU pragma: keep",
    "#include <utility> // IWYU pragma: keep",
    "#include <vector> // IWYU pragma: keep",
    "using namespace std;",
}

return imports
